// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	models "projects/LDmitryLD/petstore/app/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Storeger is an autogenerated mock type for the Storeger type
type Storeger struct {
	mock.Mock
}

// Create provides a mock function with given fields: order
func (_m *Storeger) Create(order models.Order) models.Order {
	ret := _m.Called(order)

	var r0 models.Order
	if rf, ok := ret.Get(0).(func(models.Order) models.Order); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *Storeger) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *Storeger) GetByID(id int) (models.Order, error) {
	ret := _m.Called(id)

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Order, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.Order); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Inventory provides a mock function with given fields:
func (_m *Storeger) Inventory() map[string]interface{} {
	ret := _m.Called()

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// NewStoreger creates a new instance of Storeger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storeger {
	mock := &Storeger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
